### ISSUE TITLE
As a scrummy particpant, I would like to know who is watching

### ISSUE THREAD

**Issue by nikgregory** [smatyas/scrummy#1]
Since people who do not vote should not have a card, we cannot see who might be watching.
it would be nice to have a list of watchers somewhere in the UI so we know that Rok or Will or Erik are hanging around.

**Comment by smatyas** [comment]
It's done.

The master branch of my fork contains both features I've implemented: https://github.com/smatyas/scrummy/tree/master

I've created a PR for the original project: https://github.com/tsmith512/scrummy/pull/38
